/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICloseHandler,
  ICloseHandlerInterface,
} from "../../../contracts/exchange/ICloseHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "positionId",
            type: "uint256",
          },
        ],
        internalType: "struct CloseUtils.CloseParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "executeClose",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICloseHandler__factory {
  static readonly abi = _abi;
  static createInterface(): ICloseHandlerInterface {
    return new Interface(_abi) as ICloseHandlerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICloseHandler {
    return new Contract(address, _abi, runner) as unknown as ICloseHandler;
  }
}
