/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDepositHandler,
  IDepositHandlerInterface,
} from "../../../contracts/exchange/IDepositHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "positionId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "token0",
            type: "address",
          },
          {
            internalType: "address",
            name: "token1",
            type: "address",
          },
          {
            internalType: "uint8",
            name: "tokenIndex",
            type: "uint8",
          },
        ],
        internalType: "struct DepositUtils.DepositParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "executeDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDepositHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IDepositHandlerInterface {
    return new Interface(_abi) as IDepositHandlerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDepositHandler {
    return new Contract(address, _abi, runner) as unknown as IDepositHandler;
  }
}
