/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRepayHandler,
  IRepayHandlerInterface,
} from "../../../contracts/exchange/IRepayHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "positionId",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "tokenIndex",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "repayAmount",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "repayOption",
            type: "uint8",
          },
        ],
        internalType: "struct RepayUtils.RepayParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "executeRepay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRepayHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IRepayHandlerInterface {
    return new Interface(_abi) as IRepayHandlerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRepayHandler {
    return new Contract(address, _abi, runner) as unknown as IRepayHandler;
  }
}
