/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWithdrawHandler,
  IWithdrawHandlerInterface,
} from "../../../contracts/exchange/IWithdrawHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "positionId",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "tokenIndex",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "withdrawAmount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
        ],
        internalType: "struct WithdrawUtils.WithdrawParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "executeWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWithdrawHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IWithdrawHandlerInterface {
    return new Interface(_abi) as IWithdrawHandlerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWithdrawHandler {
    return new Contract(address, _abi, runner) as unknown as IWithdrawHandler;
  }
}
