/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPoolInterestRateStrategy } from "./IPoolInterestRateStrategy";
export type { PoolInterestRateStrategy } from "./PoolInterestRateStrategy";
