/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  PoolUtils,
  PoolUtilsInterface,
} from "../../../contracts/pool/PoolUtils";

const _abi = [
  {
    inputs: [],
    name: "IGNORE_CALC_AVAILABLE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "IGNORE_CALC_LOAN",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MINIMUM_LIQUIDITY",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x610110610052600b82828239805160001a6073146045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060475760003560e01c8063783d097114604c578063ba9a7a56146066578063dd2e0a60146080575b600080fd5b6052609a565b604051605d919060c1565b60405180910390f35b606c609f565b6040516077919060c1565b60405180910390f35b608660a5565b6040516091919060c1565b60405180910390f35b600081565b6103e881565b600081565b6000819050919050565b60bb8160aa565b82525050565b600060208201905060d4600083018460b4565b9291505056fea2646970667358221220f3f02c1c4b919cc814d96a42f8a79524baa66a9a0ada6f58b3f241a84d080f3064736f6c634300081c0033";

type PoolUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PoolUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PoolUtils__factory extends ContractFactory {
  constructor(...args: PoolUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PoolUtils & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PoolUtils__factory {
    return super.connect(runner) as PoolUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoolUtilsInterface {
    return new Interface(_abi) as PoolUtilsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): PoolUtils {
    return new Contract(address, _abi, runner) as unknown as PoolUtils;
  }
}
