/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Position,
  PositionInterface,
} from "../../../contracts/position/Position";

const _abi = [
  {
    inputs: [],
    name: "CREATE_POSITION_ID",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LONG",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "NONE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SHORT",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61018a610052600b82828239805160001a6073146045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100565760003560e01c8063561cce0a1461005b5780638352539414610079578063a871da9114610097578063db968532146100b5575b600080fd5b6100636100d3565b6040516100709190610105565b60405180910390f35b6100816100d8565b60405161008e9190610105565b60405180910390f35b61009f6100dd565b6040516100ac9190610105565b60405180910390f35b6100bd6100e2565b6040516100ca9190610139565b60405180910390f35b600181565b600281565b600081565b627a120081565b600060ff82169050919050565b6100ff816100e9565b82525050565b600060208201905061011a60008301846100f6565b92915050565b6000819050919050565b61013381610120565b82525050565b600060208201905061014e600083018461012a565b9291505056fea264697066735822122092261a11d11e09ad1fbc016491b7a19959286bed0673a6fbc0f298c9cd2859f564736f6c634300081c0033";

type PositionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PositionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Position__factory extends ContractFactory {
  constructor(...args: PositionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Position & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Position__factory {
    return super.connect(runner) as Position__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PositionInterface {
    return new Interface(_abi) as PositionInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Position {
    return new Contract(address, _abi, runner) as unknown as Position;
  }
}
