/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ReaderPoolUtils {
  export type AssetStruct = {
    token: AddressLike;
    symbol: string;
    decimals: BigNumberish;
    borrowIndex: BigNumberish;
    borrowApy: BigNumberish;
    totalCollateral: BigNumberish;
    totalCollateralWithDebt: BigNumberish;
    totalDebtScaled: BigNumberish;
    poolBalance: BigNumberish;
    priceLiquidity: BigNumberish;
    avaiableLoan: BigNumberish;
    actualTradable: BigNumberish;
  };

  export type AssetStructOutput = [
    token: string,
    symbol: string,
    decimals: bigint,
    borrowIndex: bigint,
    borrowApy: bigint,
    totalCollateral: bigint,
    totalCollateralWithDebt: bigint,
    totalDebtScaled: bigint,
    poolBalance: bigint,
    priceLiquidity: bigint,
    avaiableLoan: bigint,
    actualTradable: bigint
  ] & {
    token: string;
    symbol: string;
    decimals: bigint;
    borrowIndex: bigint;
    borrowApy: bigint;
    totalCollateral: bigint;
    totalCollateralWithDebt: bigint;
    totalDebtScaled: bigint;
    poolBalance: bigint;
    priceLiquidity: bigint;
    avaiableLoan: bigint;
    actualTradable: bigint;
  };

  export type GetPoolStruct = {
    assets: [ReaderPoolUtils.AssetStruct, ReaderPoolUtils.AssetStruct];
    bank: AddressLike;
    interestRateStrategy: AddressLike;
    configuration: BigNumberish;
    lastUpdateTimestamp: BigNumberish;
    priceDecimals: BigNumberish;
    price: BigNumberish;
    source: AddressLike;
    shortEnabled: boolean;
    createdTimestamp: BigNumberish;
    unclaimedFee: BigNumberish;
    memeMaxDepositAmount: BigNumberish;
  };

  export type GetPoolStructOutput = [
    assets: [
      ReaderPoolUtils.AssetStructOutput,
      ReaderPoolUtils.AssetStructOutput
    ],
    bank: string,
    interestRateStrategy: string,
    configuration: bigint,
    lastUpdateTimestamp: bigint,
    priceDecimals: bigint,
    price: bigint,
    source: string,
    shortEnabled: boolean,
    createdTimestamp: bigint,
    unclaimedFee: bigint,
    memeMaxDepositAmount: bigint
  ] & {
    assets: [
      ReaderPoolUtils.AssetStructOutput,
      ReaderPoolUtils.AssetStructOutput
    ];
    bank: string;
    interestRateStrategy: string;
    configuration: bigint;
    lastUpdateTimestamp: bigint;
    priceDecimals: bigint;
    price: bigint;
    source: string;
    shortEnabled: boolean;
    createdTimestamp: bigint;
    unclaimedFee: bigint;
    memeMaxDepositAmount: bigint;
  };
}

export declare namespace ReaderPositionUtils {
  export type AssetStruct = {
    token: AddressLike;
    symbol: string;
    decimals: BigNumberish;
    balance: BigNumberish;
    debt: BigNumberish;
    netWorth: BigNumberish;
    maxRedeemAmount: BigNumberish;
    borrowApy: BigNumberish;
    equity: BigNumberish;
    equityValue: BigNumberish;
  };

  export type AssetStructOutput = [
    token: string,
    symbol: string,
    decimals: bigint,
    balance: bigint,
    debt: bigint,
    netWorth: bigint,
    maxRedeemAmount: bigint,
    borrowApy: bigint,
    equity: bigint,
    equityValue: bigint
  ] & {
    token: string;
    symbol: string;
    decimals: bigint;
    balance: bigint;
    debt: bigint;
    netWorth: bigint;
    maxRedeemAmount: bigint;
    borrowApy: bigint;
    equity: bigint;
    equityValue: bigint;
  };

  export type GetPositionStruct = {
    assets: [ReaderPositionUtils.AssetStruct, ReaderPositionUtils.AssetStruct];
    id: BigNumberish;
    account: AddressLike;
    marginLevel: BigNumberish;
    entryPrice: BigNumberish;
    IndexPrice: BigNumberish;
    pnl: BigNumberish;
    liquidationPrice: BigNumberish;
    toLiquidationPrice: BigNumberish;
  };

  export type GetPositionStructOutput = [
    assets: [
      ReaderPositionUtils.AssetStructOutput,
      ReaderPositionUtils.AssetStructOutput
    ],
    id: bigint,
    account: string,
    marginLevel: bigint,
    entryPrice: bigint,
    IndexPrice: bigint,
    pnl: bigint,
    liquidationPrice: bigint,
    toLiquidationPrice: bigint
  ] & {
    assets: [
      ReaderPositionUtils.AssetStructOutput,
      ReaderPositionUtils.AssetStructOutput
    ];
    id: bigint;
    account: string;
    marginLevel: bigint;
    entryPrice: bigint;
    IndexPrice: bigint;
    pnl: bigint;
    liquidationPrice: bigint;
    toLiquidationPrice: bigint;
  };
}

export interface ReaderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calcAmountIn"
      | "calcAmountOut"
      | "calcLiquidityOut"
      | "calcTokenPairOut"
      | "getDefaultInterestRateStrategy"
      | "getDefaultPoolConfiguration"
      | "getMarginLevelThreshold"
      | "getPools(address)"
      | "getPools(address,uint256,uint256)"
      | "getPoolsCount"
      | "getPositions"
      | "getTokenBase"
      | "getTreasury"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calcAmountIn",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calcAmountOut",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calcLiquidityOut",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calcTokenPairOut",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDefaultInterestRateStrategy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDefaultPoolConfiguration",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarginLevelThreshold",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPools(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPools(address,uint256,uint256)",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolsCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositions",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenBase",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasury",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calcAmountIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcLiquidityOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcTokenPairOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefaultInterestRateStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefaultPoolConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarginLevelThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPools(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPools(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasury",
    data: BytesLike
  ): Result;
}

export interface Reader extends BaseContract {
  connect(runner?: ContractRunner | null): Reader;
  waitForDeployment(): Promise<this>;

  interface: ReaderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calcAmountIn: TypedContractMethod<
    [
      dataStore: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      amountOut: BigNumberish,
      tokenOutIndex: BigNumberish
    ],
    [[bigint, bigint, bigint]],
    "view"
  >;

  calcAmountOut: TypedContractMethod<
    [
      dataStore: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      amountIn: BigNumberish,
      tokenInIndex: BigNumberish
    ],
    [[bigint, bigint, bigint]],
    "view"
  >;

  calcLiquidityOut: TypedContractMethod<
    [
      dataStore: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [bigint],
    "view"
  >;

  calcTokenPairOut: TypedContractMethod<
    [
      dataStore: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      liquidity: BigNumberish
    ],
    [[bigint, bigint]],
    "view"
  >;

  getDefaultInterestRateStrategy: TypedContractMethod<
    [dataStore: AddressLike],
    [string],
    "view"
  >;

  getDefaultPoolConfiguration: TypedContractMethod<
    [dataStore: AddressLike],
    [bigint],
    "view"
  >;

  getMarginLevelThreshold: TypedContractMethod<
    [dataStore: AddressLike],
    [bigint],
    "view"
  >;

  "getPools(address)": TypedContractMethod<
    [dataStore: AddressLike],
    [ReaderPoolUtils.GetPoolStructOutput[]],
    "view"
  >;

  "getPools(address,uint256,uint256)": TypedContractMethod<
    [dataStore: AddressLike, start: BigNumberish, end: BigNumberish],
    [ReaderPoolUtils.GetPoolStructOutput[]],
    "view"
  >;

  getPoolsCount: TypedContractMethod<
    [dataStore: AddressLike],
    [bigint],
    "view"
  >;

  getPositions: TypedContractMethod<
    [dataStore: AddressLike, account: AddressLike],
    [ReaderPositionUtils.GetPositionStructOutput[]],
    "view"
  >;

  getTokenBase: TypedContractMethod<[dataStore: AddressLike], [string], "view">;

  getTreasury: TypedContractMethod<[dataStore: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calcAmountIn"
  ): TypedContractMethod<
    [
      dataStore: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      amountOut: BigNumberish,
      tokenOutIndex: BigNumberish
    ],
    [[bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "calcAmountOut"
  ): TypedContractMethod<
    [
      dataStore: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      amountIn: BigNumberish,
      tokenInIndex: BigNumberish
    ],
    [[bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "calcLiquidityOut"
  ): TypedContractMethod<
    [
      dataStore: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calcTokenPairOut"
  ): TypedContractMethod<
    [
      dataStore: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      liquidity: BigNumberish
    ],
    [[bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDefaultInterestRateStrategy"
  ): TypedContractMethod<[dataStore: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDefaultPoolConfiguration"
  ): TypedContractMethod<[dataStore: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarginLevelThreshold"
  ): TypedContractMethod<[dataStore: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPools(address)"
  ): TypedContractMethod<
    [dataStore: AddressLike],
    [ReaderPoolUtils.GetPoolStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPools(address,uint256,uint256)"
  ): TypedContractMethod<
    [dataStore: AddressLike, start: BigNumberish, end: BigNumberish],
    [ReaderPoolUtils.GetPoolStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolsCount"
  ): TypedContractMethod<[dataStore: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPositions"
  ): TypedContractMethod<
    [dataStore: AddressLike, account: AddressLike],
    [ReaderPositionUtils.GetPositionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenBase"
  ): TypedContractMethod<[dataStore: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTreasury"
  ): TypedContractMethod<[dataStore: AddressLike], [string], "view">;

  filters: {};
}
