/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PositionInterface extends Interface {
  getFunction(
    nameOrSignature: "CREATE_POSITION_ID" | "LONG" | "NONE" | "SHORT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CREATE_POSITION_ID",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "LONG", values?: undefined): string;
  encodeFunctionData(functionFragment: "NONE", values?: undefined): string;
  encodeFunctionData(functionFragment: "SHORT", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CREATE_POSITION_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "LONG", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "NONE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SHORT", data: BytesLike): Result;
}

export interface Position extends BaseContract {
  connect(runner?: ContractRunner | null): Position;
  waitForDeployment(): Promise<this>;

  interface: PositionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATE_POSITION_ID: TypedContractMethod<[], [bigint], "view">;

  LONG: TypedContractMethod<[], [bigint], "view">;

  NONE: TypedContractMethod<[], [bigint], "view">;

  SHORT: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATE_POSITION_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LONG"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NONE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SHORT"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
