/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RoleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CONFIG_KEEPER"
      | "CONTROLLER"
      | "FEE_DISTRIBUTION_KEEPER"
      | "FEE_KEEPER"
      | "GOV_TOKEN_CONTROLLER"
      | "LIMITED_CONFIG_KEEPER"
      | "LIQUIDATION_KEEPER"
      | "POOL_KEEPER"
      | "PRICING_KEEPER"
      | "ROLE_ADMIN"
      | "ROUTER_PLUGIN"
      | "TIMELOCK_ADMIN"
      | "TIMELOCK_MULTISIG"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CONFIG_KEEPER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONTROLLER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_DISTRIBUTION_KEEPER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_KEEPER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOV_TOKEN_CONTROLLER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIMITED_CONFIG_KEEPER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATION_KEEPER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_KEEPER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICING_KEEPER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROLE_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROUTER_PLUGIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_MULTISIG",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CONFIG_KEEPER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "CONTROLLER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "FEE_DISTRIBUTION_KEEPER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FEE_KEEPER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "GOV_TOKEN_CONTROLLER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIMITED_CONFIG_KEEPER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATION_KEEPER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOL_KEEPER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICING_KEEPER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ROLE_ADMIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ROUTER_PLUGIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_MULTISIG",
    data: BytesLike
  ): Result;
}

export interface Role extends BaseContract {
  connect(runner?: ContractRunner | null): Role;
  waitForDeployment(): Promise<this>;

  interface: RoleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CONFIG_KEEPER: TypedContractMethod<[], [string], "view">;

  CONTROLLER: TypedContractMethod<[], [string], "view">;

  FEE_DISTRIBUTION_KEEPER: TypedContractMethod<[], [string], "view">;

  FEE_KEEPER: TypedContractMethod<[], [string], "view">;

  GOV_TOKEN_CONTROLLER: TypedContractMethod<[], [string], "view">;

  LIMITED_CONFIG_KEEPER: TypedContractMethod<[], [string], "view">;

  LIQUIDATION_KEEPER: TypedContractMethod<[], [string], "view">;

  POOL_KEEPER: TypedContractMethod<[], [string], "view">;

  PRICING_KEEPER: TypedContractMethod<[], [string], "view">;

  ROLE_ADMIN: TypedContractMethod<[], [string], "view">;

  ROUTER_PLUGIN: TypedContractMethod<[], [string], "view">;

  TIMELOCK_ADMIN: TypedContractMethod<[], [string], "view">;

  TIMELOCK_MULTISIG: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CONFIG_KEEPER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CONTROLLER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FEE_DISTRIBUTION_KEEPER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FEE_KEEPER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOV_TOKEN_CONTROLLER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LIMITED_CONFIG_KEEPER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LIQUIDATION_KEEPER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "POOL_KEEPER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PRICING_KEEPER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROLE_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROUTER_PLUGIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_MULTISIG"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
