/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TwapStoreUtilsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TWAP_AVERAGE_PRICE"
      | "TWAP_LAST_BLOCK_TIME_STAMP"
      | "TWAP_LAST_BLOCK_TIME_STAMP_BY_PERIOD"
      | "TWAP_LAST_PRICE_CUMMULATIVE_KEY"
      | "TWAP_LAST_PRICE_CUMMULATIVE_KEY_BY_PERIOD"
      | "TWAP_PERIOD"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "TWAP_AVERAGE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TWAP_LAST_BLOCK_TIME_STAMP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TWAP_LAST_BLOCK_TIME_STAMP_BY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TWAP_LAST_PRICE_CUMMULATIVE_KEY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TWAP_LAST_PRICE_CUMMULATIVE_KEY_BY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TWAP_PERIOD",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "TWAP_AVERAGE_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TWAP_LAST_BLOCK_TIME_STAMP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TWAP_LAST_BLOCK_TIME_STAMP_BY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TWAP_LAST_PRICE_CUMMULATIVE_KEY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TWAP_LAST_PRICE_CUMMULATIVE_KEY_BY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TWAP_PERIOD",
    data: BytesLike
  ): Result;
}

export interface TwapStoreUtils extends BaseContract {
  connect(runner?: ContractRunner | null): TwapStoreUtils;
  waitForDeployment(): Promise<this>;

  interface: TwapStoreUtilsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TWAP_AVERAGE_PRICE: TypedContractMethod<[], [string], "view">;

  TWAP_LAST_BLOCK_TIME_STAMP: TypedContractMethod<[], [string], "view">;

  TWAP_LAST_BLOCK_TIME_STAMP_BY_PERIOD: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  TWAP_LAST_PRICE_CUMMULATIVE_KEY: TypedContractMethod<[], [string], "view">;

  TWAP_LAST_PRICE_CUMMULATIVE_KEY_BY_PERIOD: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  TWAP_PERIOD: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TWAP_AVERAGE_PRICE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TWAP_LAST_BLOCK_TIME_STAMP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TWAP_LAST_BLOCK_TIME_STAMP_BY_PERIOD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TWAP_LAST_PRICE_CUMMULATIVE_KEY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TWAP_LAST_PRICE_CUMMULATIVE_KEY_BY_PERIOD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TWAP_PERIOD"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
