/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CloseUtils {
  export type CloseParamsStruct = { positionId: BigNumberish };

  export type CloseParamsStructOutput = [positionId: bigint] & {
    positionId: bigint;
  };
}

export interface ICloseHandlerInterface extends Interface {
  getFunction(nameOrSignature: "executeClose"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "executeClose",
    values: [AddressLike, CloseUtils.CloseParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeClose",
    data: BytesLike
  ): Result;
}

export interface ICloseHandler extends BaseContract {
  connect(runner?: ContractRunner | null): ICloseHandler;
  waitForDeployment(): Promise<this>;

  interface: ICloseHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeClose: TypedContractMethod<
    [account: AddressLike, params: CloseUtils.CloseParamsStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeClose"
  ): TypedContractMethod<
    [account: AddressLike, params: CloseUtils.CloseParamsStruct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
