/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace DepositUtils {
  export type DepositParamsStruct = {
    positionId: BigNumberish;
    token0: AddressLike;
    token1: AddressLike;
    tokenIndex: BigNumberish;
  };

  export type DepositParamsStructOutput = [
    positionId: bigint,
    token0: string,
    token1: string,
    tokenIndex: bigint
  ] & {
    positionId: bigint;
    token0: string;
    token1: string;
    tokenIndex: bigint;
  };
}

export interface IDepositHandlerInterface extends Interface {
  getFunction(nameOrSignature: "executeDeposit"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "executeDeposit",
    values: [AddressLike, DepositUtils.DepositParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeDeposit",
    data: BytesLike
  ): Result;
}

export interface IDepositHandler extends BaseContract {
  connect(runner?: ContractRunner | null): IDepositHandler;
  waitForDeployment(): Promise<this>;

  interface: IDepositHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeDeposit: TypedContractMethod<
    [account: AddressLike, params: DepositUtils.DepositParamsStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeDeposit"
  ): TypedContractMethod<
    [account: AddressLike, params: DepositUtils.DepositParamsStruct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
