/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace LiquidationUtils {
  export type LiquidationParamsStruct = {
    account: AddressLike;
    positionId: BigNumberish;
  };

  export type LiquidationParamsStructOutput = [
    account: string,
    positionId: bigint
  ] & { account: string; positionId: bigint };
}

export interface ILiquidationHandlerInterface extends Interface {
  getFunction(nameOrSignature: "executeLiquidation"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "executeLiquidation",
    values: [AddressLike, LiquidationUtils.LiquidationParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeLiquidation",
    data: BytesLike
  ): Result;
}

export interface ILiquidationHandler extends BaseContract {
  connect(runner?: ContractRunner | null): ILiquidationHandler;
  waitForDeployment(): Promise<this>;

  interface: ILiquidationHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeLiquidation: TypedContractMethod<
    [liquidator: AddressLike, params: LiquidationUtils.LiquidationParamsStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeLiquidation"
  ): TypedContractMethod<
    [liquidator: AddressLike, params: LiquidationUtils.LiquidationParamsStruct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
