/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RedeemUtils {
  export type RedeemParamsStruct = {
    positionId: BigNumberish;
    tokenIndex: BigNumberish;
    redeemAmount: BigNumberish;
    to: AddressLike;
  };

  export type RedeemParamsStructOutput = [
    positionId: bigint,
    tokenIndex: bigint,
    redeemAmount: bigint,
    to: string
  ] & {
    positionId: bigint;
    tokenIndex: bigint;
    redeemAmount: bigint;
    to: string;
  };
}

export interface IRedeemHandlerInterface extends Interface {
  getFunction(nameOrSignature: "executeRedeem"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "executeRedeem",
    values: [AddressLike, RedeemUtils.RedeemParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeRedeem",
    data: BytesLike
  ): Result;
}

export interface IRedeemHandler extends BaseContract {
  connect(runner?: ContractRunner | null): IRedeemHandler;
  waitForDeployment(): Promise<this>;

  interface: IRedeemHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeRedeem: TypedContractMethod<
    [account: AddressLike, params: RedeemUtils.RedeemParamsStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeRedeem"
  ): TypedContractMethod<
    [account: AddressLike, params: RedeemUtils.RedeemParamsStruct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
