/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace LiquidityUtils {
  export type AddParamsStruct = {
    token0: AddressLike;
    token1: AddressLike;
    to: AddressLike;
  };

  export type AddParamsStructOutput = [
    token0: string,
    token1: string,
    to: string
  ] & { token0: string; token1: string; to: string };

  export type RemoveParamsStruct = {
    token0: AddressLike;
    token1: AddressLike;
    liquidity: BigNumberish;
    to: AddressLike;
  };

  export type RemoveParamsStructOutput = [
    token0: string,
    token1: string,
    liquidity: bigint,
    to: string
  ] & { token0: string; token1: string; liquidity: bigint; to: string };
}

export interface LiquidityHandlerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dataStore"
      | "eventEmitter"
      | "executeAdd"
      | "executeRemove"
      | "roleStore"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "dataStore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "eventEmitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeAdd",
    values: [AddressLike, LiquidityUtils.AddParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRemove",
    values: [AddressLike, LiquidityUtils.RemoveParamsStruct]
  ): string;
  encodeFunctionData(functionFragment: "roleStore", values?: undefined): string;

  decodeFunctionResult(functionFragment: "dataStore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eventEmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executeAdd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeRemove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roleStore", data: BytesLike): Result;
}

export interface LiquidityHandler extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidityHandler;
  waitForDeployment(): Promise<this>;

  interface: LiquidityHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dataStore: TypedContractMethod<[], [string], "view">;

  eventEmitter: TypedContractMethod<[], [string], "view">;

  executeAdd: TypedContractMethod<
    [account: AddressLike, AddParams: LiquidityUtils.AddParamsStruct],
    [void],
    "nonpayable"
  >;

  executeRemove: TypedContractMethod<
    [account: AddressLike, removeParams: LiquidityUtils.RemoveParamsStruct],
    [void],
    "nonpayable"
  >;

  roleStore: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dataStore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eventEmitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeAdd"
  ): TypedContractMethod<
    [account: AddressLike, AddParams: LiquidityUtils.AddParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeRemove"
  ): TypedContractMethod<
    [account: AddressLike, removeParams: LiquidityUtils.RemoveParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleStore"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
