/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type CreatePoolParamsStruct = {
  token: AddressLike;
  source: AddressLike;
};

export type CreatePoolParamsStructOutput = [token: string, source: string] & {
  token: string;
  source: string;
};

export declare namespace Pool {
  export type AssetStruct = {
    token: AddressLike;
    borrowIndex: BigNumberish;
    borrowRate: BigNumberish;
    totalCollateral: BigNumberish;
    totalCollateralWithDebt: BigNumberish;
    totalDebtScaled: BigNumberish;
    unclaimedFee: BigNumberish;
  };

  export type AssetStructOutput = [
    token: string,
    borrowIndex: bigint,
    borrowRate: bigint,
    totalCollateral: bigint,
    totalCollateralWithDebt: bigint,
    totalDebtScaled: bigint,
    unclaimedFee: bigint
  ] & {
    token: string;
    borrowIndex: bigint;
    borrowRate: bigint;
    totalCollateral: bigint;
    totalCollateralWithDebt: bigint;
    totalDebtScaled: bigint;
    unclaimedFee: bigint;
  };

  export type PropsStruct = {
    assets: [Pool.AssetStruct, Pool.AssetStruct];
    bank: AddressLike;
    interestRateStrategy: AddressLike;
    configuration: BigNumberish;
    lastUpdateTimestamp: BigNumberish;
  };

  export type PropsStructOutput = [
    assets: [Pool.AssetStructOutput, Pool.AssetStructOutput],
    bank: string,
    interestRateStrategy: string,
    configuration: bigint,
    lastUpdateTimestamp: bigint
  ] & {
    assets: [Pool.AssetStructOutput, Pool.AssetStructOutput];
    bank: string;
    interestRateStrategy: string;
    configuration: bigint;
    lastUpdateTimestamp: bigint;
  };
}

export interface PoolFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createPool" | "dataStore" | "roleStore"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createPool",
    values: [CreatePoolParamsStruct]
  ): string;
  encodeFunctionData(functionFragment: "dataStore", values?: undefined): string;
  encodeFunctionData(functionFragment: "roleStore", values?: undefined): string;

  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dataStore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roleStore", data: BytesLike): Result;
}

export interface PoolFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PoolFactory;
  waitForDeployment(): Promise<this>;

  interface: PoolFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPool: TypedContractMethod<
    [params: CreatePoolParamsStruct],
    [Pool.PropsStructOutput],
    "nonpayable"
  >;

  dataStore: TypedContractMethod<[], [string], "view">;

  roleStore: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [params: CreatePoolParamsStruct],
    [Pool.PropsStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dataStore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "roleStore"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
